### ISSUE TITLE
[bug] Have better unicode support for text fields

### ISSUE THREAD

**Issue by saresend** [HackSC/odyssey#77]

**Comment by saresend** [comment]
![image](https://user-images.githubusercontent.com/20709220/68278512-5438fe80-0026-11ea-8898-7d05818912d2.png)

Saving emojis and chinese characters evidently renders as `?` on save

**Comment by WilhelmWillie** [comment]
i think this was mostly a DB issue because MySQL doesn't support unicode by default. ran `ALTER TABLE production.HackerProfiles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin` which seems to have fixed things 

<img width="1051" alt="Screen Shot 2019-11-06 at 12 12 54 AM" src="https://user-images.githubusercontent.com/4969041/68280397-4e451c80-002a-11ea-9f58-22233e9486ee.png">

**Comment by WilhelmWillie** [comment]
Was able to save an app w/ Chinese characters, I think we're good

**Comment by saresend** [comment]
On Prod?
